version: "3.8"

include:
  - ../../docker-compose.yml

services:
  app-backend:
    image: upiksaleh/codeup-app-backend:main
    container_name: app-backend
    restart: unless-stopped
    environment:
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
    env_file:
      - .env
    networks:
      - backend
    
